### ISSUE TITLE
Bearbeiten und Löschen

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/frontend#108]
Das letzte große Feature, das noch fehlt, ist das Bearbeiten und Löschen. Da wir dabei einige durchaus anspruchsvolle Wünsche haben, werden wir diese Aufgabe in mehreren Issues aufteilen.

## Funktionalität

Nur die Angebotsübersichtsseite (`OfferChangeComponent`) wird angepasst. Auf der soll man alle Daten bearbeiten, weitere Ressourcen hinzufügen und entfernen können. Hier ist ein Link zu einer aktuellen Angebotsübersichtsseite: http://pirat.chaoran-chen.de/change/AvpE0unjBcHiQOjwN695sRzEnkqD1m

Eine wichtige Funktionalität ist, dass wir aufzeichnen wollen, wie viele Ressourcen wir verteilt werden. Der Nutzer muss also angeben, was der Grund für ein Entfernen ist: ob er es nicht mehr anbieten will, über einen anderen Kanal vergeben hat und über uns.

## Verlinkte Issues (in der Reihenfolge bearbeiten)

- [x] #109
- [x] #110 
- [x] #111
- [ ] #112
- [x] #113

**Comment by BJRWolf** [comment]
Das Design steht soweit. Jetzt fehlt noch das Skript, damit die Values an den richtigen Stellen übertragen werden

**Comment by chaoran-chen** [comment]
#112 wird wann anders gemacht.
