### ISSUE TITLE
Anzahl einer Ressource verringern bzw. Ressource löschen

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/frontend#111]
Die Anzahl der bereitgestellten Einheiten einer Ressource soll verringert werden können. (D.h. statt 30 Packungen Handschuhe runter auf nur 10.) Außerdem soll das Löschen möglich sein. Dabei muss man allerdings einen Grund angeben:

+ Ressource wurde über unsere Plattform vermittelt und vergeben
+ Ressource wurde über einen anderen Weg vergeben
+ Ressource soll nicht mehr angeboten werden
+ Sonstiges (Freifeld)

**Comment by BJRWolf** [comment]
Anzahl soll verringert und gelöscht, aber nicht erhöht werden können? Und gilt das für Geräte und Verbrauchsmaterial?

**Comment by BJRWolf** [comment]
In #113 steht Anzahl der Ressourcen soll auch erhöht werden können... Also Anzahl soll erhöht, verringert und gelöscht werden können?

**Comment by chaoran-chen** [comment]
Ja, genau, alles geht. Aber beim Löschen und Verringern muss man einen Grund auswählen, beim Erhöhen nciht.
