### ISSUE TITLE
Language switchers contain hardcoded link

### ISSUE THREAD

**Issue by dhach** [COVID19-PIRAT/frontend#138]
The links to switch languages have a hard-coded target. It does not respect the current domain.
This makes running a personal deployment, or one not associated with the original domain, more difficult.

rendered HTML of language switchers:
`<a _ngcontent-sga-c44="" class="active" href="#">de</a> / <a _ngcontent-sga-c44="" href="https://en.pirat-tool.com/en/">en</a> / <a _ngcontent-sga-c44="" href="https://it.pirat-tool.com/it/">it</a>`

**Comment by chaoran-chen** [comment]
That's easy to change, I will do it right away.
