### ISSUE TITLE
Remove resources that have been added before

### ISSUE THREAD

**Issue by MaxWies** [COVID19-PIRAT/frontend#190]
When I create a new offer I might add a wrong resource. However, I am not able to remove the resource anymore and have to reload the page and loose my inputs.

A small X button in the upper right corner of an added resource would be nice to remove it easily.

**Comment by chaoran-chen** [comment]
![image](https://user-images.githubusercontent.com/18666552/81487655-8cccc580-925f-11ea-9497-f8a46fd53917.png)

?
