### ISSUE TITLE
Formulare: Verpflichtende Felder festlegen

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/frontend#22]
Notwendige Formulareingaben (welche?) sind als verpflichtend zu markieren.

**Comment by lvordemann** [comment]
- Allgemein: Organisation, Verantwortliche Person, Email
- Helfer: Qualifikation, Institution, Bereich und PCR, Checkbox Ehrenamt
- Gerät: Kategorie, Materialbezeichnung, Hersteller, Bestellnummer, Standort, Menge, Maßeinheit
- Verbrauchsmaterial: Kategorie, Bezeichnung, Hersteller, Standort, Menge, Maßeinheit-

**Comment by lvordemann** [comment]
Datenschutzerklärung in neuem Fenster öffnen und nicht im Selben Window
