### ISSUE TITLE
Andere Optionen bei Qualifikation und Gebrauchsmaterial entfernen

### ISSUE THREAD

**Issue by lvordemann** [COVID19-PIRAT/frontend#32]
Auch bei der Suchanfrage entfernen. DA wir keine Tabelle haben müsste der Freitext ansonsten genau Matchen.

**Comment by chaoran-chen** [comment]
War das das, worüber wir vorhin geredet haben?

Ich verstehe das Problem mit der Option "Sonstiges" nicht.

**Comment by lvordemann** [comment]
Gibt auch kein Problem.
