### ISSUE TITLE
Bestätigung der Offer

### ISSUE THREAD

**Issue by lvordemann** [COVID19-PIRAT/frontend#38]
Hinzufügen einer Alert Box oder anderweitigen Benachrichtigung, dass das Angebot korrekt gespeichert wurde und eine Email verschickt wurde.

- [x] Möglichkeit zum Löschen (Backend sollte heute noch nachziehen)
- [ ] Bearbeitungsoptionen (Nur gemockt erstmal, backend kommt post-hackathon )
- [ ] QR-Code für die Geräte (https://github.com/COVID19-PIRAT/frontend/issues/38, backend vermutlich auch erst post-hackathon)

**Comment by lvordemann** [comment]
Notizen fürs Backend:
- DELETE request löscht momentan nur den Link aus der Datenbank

**Comment by chaoran-chen** [comment]
Die fehlende Teile wurden in andere Issues ausgelagert.
