### ISSUE TITLE
Kontaktdaten anonymisieren

### ISSUE THREAD

**Issue by lvordemann** [COVID19-PIRAT/frontend#66]
Der Ersteller eines Angebots soll die Auswahl haben seine Kontaktdatenzu anonymisierten oder öffentlich zur verfügung zu stellen. Bei Anonymisierung wird ein Kontaktformular angeboten, über das man die Person erreichen kann. Das Kontaktformular wird mit reCAPTCHA geschützt.

Backend: https://github.com/COVID19-PIRAT/backend/issues/13

**Comment by chaoran-chen** [comment]
Diese Funktion sehe ich als notwendig für einen Release an.
