### ISSUE TITLE
Developer Hinweis auf Landing Page

### ISSUE THREAD

**Issue by lvordemann** [COVID19-PIRAT/frontend#67]
Hinweis auf Landing Page, dass die Seite auf Hochtouren entwickelt wird und man kann sich mit seiner Email eintragen um über den Release informiert zu werden.

**Comment by lvordemann** [comment]
Sehr wichtig, da wir so etwas Zeit gewinnen, wenn Leute schonmal die Seite aufrufen.

**Comment by chaoran-chen** [comment]
Erledigt in 125d7a9b9864ae03933efafaad37da761ff28857 (ohne Emaileintrage).
