### ISSUE TITLE
Distanzangabe bei der Suche

### ISSUE THREAD

**Issue by chaoran-chen** [COVID19-PIRAT/frontend#75]
Bei der Anfrage für die Suche soll die gewünschte Distanz übergeben werden.

Die Resultate sollen nach Distanz sortiert und die Distanzangaben angezeigt werden.

**Comment by lvordemann** [comment]
Distanzanzeige als Slider realisieren

**Comment by chaoran-chen** [comment]
Das würde ich in einem anderen Issue bearbeiten.
