### ISSUE TITLE
Neues Gerät lässt sich nicht erstellen

### ISSUE THREAD

**Issue by Julia91457** [COVID19-PIRAT/frontend#77]
![grafik](https://user-images.githubusercontent.com/62450348/77524263-55f54880-6e87-11ea-9fd4-8d885581e9c1.png)
mit den gezeigten Eingaben passiert bei Klick auf Angebot erstellen nichts

**Comment by chaoran-chen** [comment]
Problem liegt an https://github.com/COVID19-PIRAT/backend/issues/18

**Comment by chaoran-chen** [comment]
Behoben.
