### ISSUE TITLE
Problem bei mehreren Geräten

### ISSUE THREAD

**Issue by ELIESCH** [COVID19-PIRAT/frontend#78]
Ich versuche gerade 3 Geräte einzustellen und das geht irgendwie auch nicht vielleicht funktionierts nicht wenn man zu viele gleichzeitig machen will?

--> habs nochmal probiert und diesmal gleich nach dem ersten Gerät das Roboter Dings gemacht dann konnte ich 3 Geräte reinstellen

**Comment by chaoran-chen** [comment]
Kannst du reproduzieren, wann es nicht geht und die Screenshots reinstellen?

**Comment by ELIESCH** [comment]
Problem konnte nicht reproduziert werden jetzt gehts

**Comment by chaoran-chen** [comment]
Okay, dann schließe ich das erstmal. Gerne wieder aufmachen, wenn's wieder passiert.
