### ISSUE TITLE
Angebote bearbeiten

### ISSUE THREAD

**Issue by ELIESCH** [COVID19-PIRAT/frontend#79]
Hi man kann Angebote leider nicht bearbeiten es gibt nur die option löschen. Die allerdings auch nicht funktioniert. Ich hab versucht das Angebot von Wissenschaftler 2 zu löschen.

**Comment by lvordemann** [comment]
Diese Funktionalität wurde vorerst deaktiviert aufgrund von backend Problemen. Hinweis zum Löschen der Offer der Mail wurde auf Seite platziert. Funktionalität des bearbeiten und löschen wird in den nächsten Tagen eingefügt.
