### ISSUE TITLE
Personal anbieten geht garnicht

### ISSUE THREAD

**Issue by ELIESCH** [COVID19-PIRAT/frontend#80]
![Personal_problem](https://user-images.githubusercontent.com/36033823/77525412-4971ef80-6e89-11ea-86ac-f1381eb67f79.jpeg)
![Personal_problem_2](https://user-images.githubusercontent.com/36033823/77525417-4aa31c80-6e89-11ea-8714-4aacb3912204.jpeg)

Es scheint, dass der checkmark am Ende das Problem ist

**Comment by chaoran-chen** [comment]
Das Problem besteht auch bei Desktopgeräten.

**Comment by lvordemann** [comment]
Problem was a misspelled variable declaration
